typography_spectrum: 0.5522559282835573
color:
  brandColors:
    - '#FCFCFC'
    - '#040807'
    - '#4E4A47'
    - '#9A9B9D'
    - '#DBC884'
  brandStrength: 0.07627103663980961
  lightness: 0.18153720977716148
  rhythmicContrast: 0.7997996234335005
  saturation: 0.07565063005313277
github: true
layout_spectrum: 0.28788278228603303
analytics:
  google: UA-78475073-1
author:
  name: Daniel Swid
name: Portfolio
url: 'http://daniel.swidnikk.com/'
title: Daniel
content: []
description: 'The what, why, and how you want to know.'
purpose:
  - type: external
    url: 'http://calendly.com/swidnikk/hello'
    label: Say Hello.
